### ISSUE TITLE
not enough arguments in call

### ISSUE THREAD

**Issue by retgits** [thundra-io/thundra-lambda-agent-go#6]
In my code I have:
```
func main() {
	// Instantiate Thundra Agent with Trace Support
	t := thundra.NewBuilder().AddPlugin(&trace.Trace{}).SetAPIKey("xxx").Build()

	// Wrap your lambda function with Thundra
	lambda.Start(thundra.Wrap(Handle, t))
}
```

When I try to build my app, it fails with the error:
```
vendor/github.com/thundra-io/thundra-lambda-agent-go/trace/trace.go:120:22: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
```

Changing line 122 in [trace.go](https://github.com/thundra-io/thundra-lambda-agent-go/blob/master/trace/trace.go#L120) from `uniqueId = uuid.Must(uuid.NewV4())` to `uniqueId = uuid.Must(uuid.NewV4(), nil)` fixes the issue and results in a successful build of my app (and also results in data being sent to Thundra). If you want I can contribute a patch 😄

**Comment by serkan-ozal** [comment]
Hi @retgits 

Thanks for reporting the issue. I think this is a dependency resoulution problem for the `go.uuid` library. We should add it as vendor to our project to prevent such kind of problems.

It will be fixed as soon as possible and notify you once it is fixed. Lets keep the issue open until fixed.

By the way, good to know that you can monitor your AWS Lambda Go functions with Thundra :)

There are more features coming for Go agent. Stay tuned!!!

**Comment by efemedgy** [comment]
Thanks @retgits,

I have added golang/dep support to prevent these problems from happening again. #11
