### ISSUE TITLE
Go agent doesn't read the environment variable in Lambda

### ISSUE THREAD

**Issue by retgits** [thundra-io/thundra-lambda-agent-go#7]
As suggested creating an issue here. 

When I followed the instructions in the docs on [Configuration](https://docs.thundra.io/docs/configuration) and only supply the environment variable, I got an error like below. When I hardcoded the API key, it worked perfectly

```
response Body:
{
  "timestamp": 1521857820679,
  "status": 401,
  "error": "Unauthorized",
  "message": "No API key provided",
  "path": "/api/monitor-datas"
}
```

**Comment by serkan-ozal** [comment]
@retgits Thanks for reporting the issue.

@efemedgy according to doc https://docs.thundra.io/docs/configuration, this https://github.com/thundra-io/thundra-lambda-agent-go/blob/7ac1749a22539ae3deed4b7bc6b7893c16e72a55/thundra/constants.go#L7 must be `thundra_apiKey` not `thundraApiKey`

**Comment by serkan-ozal** [comment]
@retgits 

For now, if you want to go through with environment variables, you can use `thundraApiKey` as environment variable for API key. 

However, once this issue is fixed, you must change it back to `thundra_apiKey` as stated in the doc.

**Comment by serkan-ozal** [comment]
Hi @retgits,

The issue has been fixed. You can configure your API key with `thundra_apiKey` environment variable as stated in the doc.
