### ISSUE TITLE
Disabling lambda request/response tracing does not work

### ISSUE THREAD

**Issue by skayle-denis** [thundra-io/thundra-lambda-agent-go#86]
Looks like 

```
const ThundraDisableTraceRequest = "thundra_agent_lambda_trace_request_disable"
const ThundraDisableTraceResponse = "thundra_agent_lambda_trace_response_disable"
```

variables are ignored and the lambda request and response are always added to the trace.

**Comment by serkan-ozal** [comment]
Thanks for reporting the issue @skayle-denis We will look into that and fix asap

**Comment by fatihaydilek** [comment]
Hi @skayle-denis you can disable request/response in Thundra by adding these environment variables in your function
`thundra_agent_lambda_trace_request_skip`
`thundra_agent_lambda_trace_response_skip`
